plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.cppnativeapp'
    compileSdk 34
    ndkVersion '25.1.8937393'

    defaultConfig {
        applicationId "com.example.cppnativeapp"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake { cppFlags "" }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }
}
