name: Build Native C++ APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle Environment
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK with Gradle
        run: gradle assembleDebug --stacktrace

      - name: Upload Generated APK
        uses: actions/upload-artifact@v4
        with:
          name: Native-Cpp-APK-Debug
          path: app/build/outputs/apk/debug/app-debug.apk